default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: test
  password: "test"

development:
  <<: *default
  database: test_dev


test:
  <<: *default
  database: test_test