default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: binomo
  password: "576526"

development:
  <<: *default
  database: testpoj_dev


test:
  <<: *default
  database: testpoj_test