#
# Symmetric Encryption for Ruby
#
---
# For the development and test environments the test symmetric encryption keys
# can be placed directly in the source code.
# And therefore no RSA private key is required
development:         &development_defaults
  key:               1234567890ABCDEF1234567890ABCDEF
  iv:                1234567890ABCDEF
  cipher_name:       aes-128-cbc
  encoding:          :base64strict
  always_add_header: true

test:
  <<: *development_defaults

release:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpQIBAAKCAQEAoxQt9FuvIGbHXNjrbqFXaHjluZIfNiUq2BOBGXrL5eE8rOCL
    a+2LcMVBMmeGomrVbSMZHoWH5vyegr4g3UiIOJQyirj3oE4e78E3gqX/y2YwfCTj
    r65evDxcfH8PDgy2YJX/CF74ktWzXe1Pp/7v65mqN9Gi1W2HVr8V2rgU+FdMIt1U
    XmgOkyG25LTdSfvyjgVbtdezdfZuodnIgQoo9iT6sJMzMiIZG02YX4MFdy70QEc4
    3py0ukJJvuaB/GW5TE/2jISzyFd192hxSqljyxVRItIvhxgHi9d2HNLgsJEnZbdr
    WDLijqMReFLxPuvIXp2ZbSoXaH8/6+bRrs/uEwIDAQABAoIBAG7mkjnS/81xF7K0
    cabSYbbSQKdqD3+q1vAKk4jYUUELY0/NhALpkCIogqXccVqSfIGzlKmE9V7H/KO8
    2Gyjnr+bSKO+FegWOEOjijR23vVbkS1biNs4IYSxJ9QiNALB8mTMnJr8ut5gJZKC
    h+EfJdl6rp83GR07VwZO/HW5KcmXvg8/QlZBEYm4giD7PY6+8tYs5o6guMyds+dH
    8uZBDxrSuigF8BnF30rQOkt9RiTXNB8Uq4UdjswoMwYkosy7Cf3tc+5oiLdAdDwl
    KhEtn5BbbLAV2/abuIX+vzRkcbstyDV9lGdrdH/weCTKxXB74u1jEQMnuMjr6z1+
    IphAYgECgYEA10TUduwNlkKvHF6m0+IeI9chJnoqdTCZubaHovMhwmvWZ1vIy0o6
    oe7d/OW11r29y5jxg/IKuRN8RGudSvvlsLIsgNUo1OR+uULvKKTlkAHpXKszGuPQ
    HqykQF/x4gKr+Mv6ZE0a0PH3PRgwfkjRv7QGc5tV2YbHZaJyMQwPsmECgYEAwe9f
    wGtNmsMtvrm4Y9/SZviDRHgP5/Ej6CCadohTKa1bpK90MuDuWix8E7Yjp8Aezo0X
    bS6weQuZONjqxw3uPARiIMY4xKcLilCcihfR+fATerg3NIyJTgC/1wMecZunra+I
    TzSiuu0ybFr4nqSqrATxrtBDMZvX/s+VEbvHHPMCgYEAjzjxLuogpA9b2EE1N5Wi
    ve+804/GPdAHByNlHMosdOEwdfYAIxkQ53o4YbEniWcWJqZsUYAxGC/Zpt/+d8we
    ZrA0ocawcuxPT80zt1P2lBhhfdE9oC9f4Xi1k0sCcH+ckVyNDDyskcXa2+ADK5Ih
    Uy1geXwo4yAj+//Xf8BplSECgYEAoQg0x7/Rtpoul9n6w+OL/7iGtwnCm2Nd31eD
    Kr1T4J10JTETGVQwVmvtsyhgPuCGNBhvxVcpbbk1x0BG4nYsxWUWXgR6CsByEq2Q
    7hGNZy3z3sir/lRbhouUv+J1GvyWpN/GHY6lOPXQEq0PGBu/JAsO64s+4Ch5l7mi
    HBGB6gUCgYEA1IwV2t/nrXBgSSbErmfOTW8XaiMQa+PAtIXymuhypIZ02qjADXwC
    MYvek7Tmi7K+QqQ33MtdD0xEqHPG2DRV1Fh0gOWty6bCLk48COPqv5MWM5g1Onn9
    7tThLgH0ouL2vlakBirMCsvORH6HgyamUQdCppC/X64uo7ucf2MnKts=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      config/symmetric_encryption/adminb_release.key
      iv_filename:       config/symmetric_encryption/adminb_release.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true

production:
  # Since the key to encrypt and decrypt with must NOT be stored along with the
  # source code, we only hold a RSA key that is used to unlock the file
  # containing the actual symmetric encryption key
  private_rsa_key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEogIBAAKCAQEAs3STxXt0iKlgot04WlC8chTr/NNljfNmFzq1kt7KtqN77OqD
    F3OvmWxw/kwemawAFShAHlT2VhMv+2kxOJIjzBxxIQpSKqtoxdwOn9aV5cYLFx+X
    hs/uQyNeKHYlCYMFc4K5kwgw/iaBZSDGcyBgWU92U/fyXut+A+h4usleWx4XHHXw
    RUoMHIyub1/BqK7QG1TBT9YxB/hpHbQybSSV6F3lom2U6JzDzd0H2sPzDfQQI34w
    R51UQRLqjy+G8cnEr5AogYq9gxPcfG8Zfdh66K6jF27csC8WfMCe+KZFrW9K8mrZ
    SMOPeJbrAZMDr9DyrU9XZUgzU94yfSDgJGSzwQIDAQABAoIBADfKm5J/Akjml9Oq
    gTWa+ithk8ijlGQgcvHv37mMqGtFwmZytlTZM5O4Yhy9X5oZHmF1hRGpCnjSOE2q
    c5IJ5TU09nr2MXtwlP9GnglVdn7cJmCHAt330TRwT3q22GbvpAc4cidjGZA6OmpN
    WUU7oJjDmp8aa/DUt/XRFY/EwSAEYpHGfoXs2rsKb5BZPIGqyhc3pQVYMnNWAj24
    Vbhv1OdwILjvt1Ss+NgTXLXUk9Y/CppM5a0ZteS270cM4/EOn/S7Ou49HTjKx5KP
    z2hJ5DOAptPsVic6/+wJPedILbWFgBhFtkMs/dJVKysiUR0bRo0ZE+VKbZVCCzTI
    I+tL3o0CgYEA2hDWYuglVJ2dptD4q8GxPwKRMjQR08imEjzat7/qq9LKHfG4iJSo
    ZbCPCH4jt2Kg/i/yDm9/AJZsj5jgfC0XF3w29+TYar3NiLkf1pfA7/Zqa8AuAtos
    g1R0/nHuK85FSvPIrY0loatbBzuhytIQzDBDSO950KTl6dJKr0tqM7sCgYEA0qxL
    1OztBeYsZjtFnaMNDJehUWednj+7AZtmFQId94Mjei34DQOZ71vI8WmzrKaToMRM
    hNOkAyYCajctPm8Tr68RYDznp0ro6zKTRdzdrW5EPLYP9jl0m4mUY2s9XzfxDOBE
    iLk5+qA6c3swwd0BIBA4AcP3IitMqSBlx93LGLMCgYBM+NaD0QekR4JnaKnuDo+e
    +yv/OYv1YoTkOSDG7XJLNjtruG/3nemXA2xphgTbbXAAaTIa0FZXAcHOKhtLGatl
    +c15UQjnHJoZIadQWv6adTN5VzumfBZsQPqO+e4k/klNPKHgSMs4tsCJ3A2vBtkx
    CfQmIYmxEROqpjUAjTEukwKBgD9ILgcpnBEXkOKsjz7IyZSsv3Jac4gjkKLs8P8C
    gcnlhHSg9k/CcyzpHzUVETmdV98E2A9WG4AunK8XH+oPJ5SwO8HyyYsA/3IW4RIt
    RBFie/DYp3bIz3QhIYezoN3HSgsaGrwPF5FnK+ega4bwQfRFqu0s1kFXTFHJP4mH
    4AftAoGABX0bwTNdnRnrlAWlW4BjwVFfkld3DbPYOqBaEpE7ubjJerXLgK84JQCN
    tCY9FoVVzqfkD/hvFCb8VJ39GFbRq5gi3zAW/IJrWEuoiGLbixKQxdJgXLFWn2v5
    3XKJ5daET1XDSqYtpKnpgFDhNjXZGh3Ds0L4oIaa3WJS2l3YygM=
    -----END RSA PRIVATE KEY-----


  # List Symmetric Key files in the order of current / latest first
  ciphers:
    -
      # Filename containing Symmetric Encryption Key encrypted using the
      # RSA public key derived from the private key above
      key_filename:      config/symmetric_encryption/adminb_production.key
      iv_filename:       config/symmetric_encryption/adminb_production.iv
      cipher_name:       aes-256-cbc
      encoding:          :base64strict
      version:           1
      always_add_header: true
